# Generated by Django 5.2.15 on 2026-06-11 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_curso_profesor_jefe"),
        ("alumnos", "0002_remove_perfilalumno_curso_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("presente", "Presente"),
                            ("ausente", "Ausente"),
                            ("justificado", "Justificado"),
                            ("atrasado", "Atrasado"),
                        ],
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                (
                    "curso_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="academico.cursoasignatura",
                        verbose_name="asignatura de curso",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="alumnos.matricula",
                        verbose_name="matrícula",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de asistencia",
                "verbose_name_plural": "registros de asistencia",
                "ordering": ["-fecha", "matricula__alumno__usuario__last_name"],
                "indexes": [
                    models.Index(
                        fields=["matricula", "fecha"],
                        name="asistencia__matricu_a8d3e6_idx",
                    ),
                    models.Index(
                        fields=["curso_asignatura", "fecha"],
                        name="asistencia__curso_a_1216b6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("matricula", "curso_asignatura", "fecha"),
                        name="unique_asistencia_matricula_clase_fecha",
                    )
                ],
            },
        ),
    ]
