# Generated by Django 5.2.15 on 2026-06-12 13:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumnos", "0002_remove_perfilalumno_curso_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoArancel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "monto_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="monto base",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "tipo de arancel",
                "verbose_name_plural": "tipos de arancel",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cobro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text='Ej: "2026-03" para mensualidad de marzo, "2026-matricula".',
                        max_length=20,
                        verbose_name="período",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="monto",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="fecha de vencimiento"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagado", "Pagado"),
                            ("vencido", "Vencido"),
                            ("condonado", "Condonado"),
                        ],
                        default="pendiente",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobros",
                        to="alumnos.matricula",
                        verbose_name="matrícula",
                    ),
                ),
                (
                    "tipo_arancel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cobros",
                        to="contabilidad.tipoarancel",
                        verbose_name="tipo de arancel",
                    ),
                ),
            ],
            options={
                "verbose_name": "cobro",
                "verbose_name_plural": "cobros",
                "ordering": ["-fecha_vencimiento"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPago",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "monto_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="monto pagado",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha de pago",
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("otro", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="medio de pago",
                    ),
                ),
                (
                    "comprobante",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="comprobante adjunto",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cobro",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contabilidad.cobro",
                        verbose_name="cobro",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de pago",
                "verbose_name_plural": "historical pagos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="monto pagado",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha de pago",
                    ),
                ),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("otro", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="medio de pago",
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprobantes/%Y/%m/",
                        verbose_name="comprobante adjunto",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                (
                    "cobro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="contabilidad.cobro",
                        verbose_name="cobro",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago",
                "verbose_name_plural": "pagos",
                "ordering": ["-fecha_pago", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="cobro",
            index=models.Index(
                fields=["matricula", "estado"], name="contabilida_matricu_7ba699_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cobro",
            constraint=models.UniqueConstraint(
                fields=("matricula", "tipo_arancel", "periodo"),
                name="unique_cobro_matricula_arancel_periodo",
            ),
        ),
    ]
