# Generated by Django 5.2.15 on 2026-06-12 02:19

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumnos", "0002_remove_perfilalumno_curso_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAnotacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("positiva", "Positiva"),
                            ("negativa", "Negativa"),
                            ("observacion", "Observación"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="descripción")),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="fecha"
                    ),
                ),
                (
                    "toma_conocimiento",
                    models.BooleanField(
                        default=False, verbose_name="apoderado tomó conocimiento"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="alumnos.matricula",
                        verbose_name="matrícula",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de anotación",
                "verbose_name_plural": "historical anotaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Anotacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("positiva", "Positiva"),
                            ("negativa", "Negativa"),
                            ("observacion", "Observación"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="descripción")),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="fecha"
                    ),
                ),
                (
                    "toma_conocimiento",
                    models.BooleanField(
                        default=False, verbose_name="apoderado tomó conocimiento"
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anotaciones",
                        to="alumnos.matricula",
                        verbose_name="matrícula",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anotaciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "anotación",
                "verbose_name_plural": "anotaciones",
                "ordering": ["-fecha", "-id"],
                "indexes": [
                    models.Index(
                        fields=["matricula", "fecha"],
                        name="convivencia_matricu_2e6e5c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Citacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(verbose_name="fecha y hora")),
                ("motivo", models.TextField(verbose_name="motivo")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("realizada", "Realizada"),
                            ("ausente", "Apoderado ausente"),
                        ],
                        default="programada",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "acuerdos",
                    models.TextField(
                        blank=True,
                        help_text="Se completa al realizar la reunión.",
                        verbose_name="acuerdos",
                    ),
                ),
                (
                    "apoderado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citaciones",
                        to="alumnos.perfilapoderado",
                        verbose_name="apoderado citado",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citaciones",
                        to="alumnos.matricula",
                        verbose_name="matrícula",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citaciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "citación",
                "verbose_name_plural": "citaciones",
                "ordering": ["-fecha_hora"],
                "indexes": [
                    models.Index(
                        fields=["matricula", "fecha_hora"],
                        name="convivencia_matricu_a52822_idx",
                    )
                ],
            },
        ),
    ]
