# Generated by Django 5.2.15 on 2026-06-11 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilProfesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(max_length=100, verbose_name="especialidad"),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="título profesional"),
                ),
                (
                    "jefe_de_curso",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profesor_jefe",
                        to="academico.curso",
                        verbose_name="jefe de curso",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"role": "profesor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_profesor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de profesor",
                "verbose_name_plural": "perfiles de profesores",
                "ordering": ["usuario__last_name", "usuario__first_name"],
            },
        ),
    ]
