# Generated by Django 5.2.15 on 2026-06-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilprofesor",
            name="jefe_de_curso",
        ),
    ]
