# Generated by Django 5.2.15 on 2026-06-11 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="código"),
                ),
                (
                    "horas_semanales",
                    models.PositiveSmallIntegerField(verbose_name="horas semanales"),
                ),
            ],
            options={
                "verbose_name": "asignatura",
                "verbose_name_plural": "asignaturas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="NivelEducacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="nombre"),
                ),
            ],
            options={
                "verbose_name": "nivel educacional",
                "verbose_name_plural": "niveles educacionales",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letra", models.CharField(max_length=1, verbose_name="letra")),
                (
                    "anio_escolar",
                    models.PositiveSmallIntegerField(verbose_name="año escolar"),
                ),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        default=35, verbose_name="capacidad"
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cursos",
                        to="academico.niveleducacional",
                        verbose_name="nivel educacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "curso",
                "verbose_name_plural": "cursos",
                "ordering": ["-anio_escolar", "nivel_id", "letra"],
            },
        ),
        migrations.CreateModel(
            name="CursoAsignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio_escolar",
                    models.PositiveSmallIntegerField(verbose_name="año escolar"),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curso_asignaturas",
                        to="academico.asignatura",
                        verbose_name="asignatura",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curso_asignaturas",
                        to="academico.curso",
                        verbose_name="curso",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        limit_choices_to={"role": "profesor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaturas_dictadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "asignatura de curso",
                "verbose_name_plural": "asignaturas de curso",
                "ordering": ["-anio_escolar", "curso_id", "asignatura__nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("curso", "asignatura", "anio_escolar"),
                        name="unique_cursoasignatura_curso_asignatura_anio",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="curso",
            constraint=models.UniqueConstraint(
                fields=("nivel", "letra", "anio_escolar"),
                name="unique_curso_nivel_letra_anio",
            ),
        ),
    ]
