# Generated by Django 5.2.15 on 2026-06-11 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
        ("profesores", "0002_remove_perfilprofesor_jefe_de_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="profesor_jefe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jefaturas",
                to="profesores.perfilprofesor",
                verbose_name="profesor jefe",
            ),
        ),
    ]
