# Generated by Django 5.2.15 on 2026-06-12 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0002_curso_profesor_jefe"),
        ("calificaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        blank=True,
                        help_text='Ej: "Unidad 1: Fracciones" (opcional).',
                        max_length=100,
                        verbose_name="unidad",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="título")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="materiales/%Y/", verbose_name="archivo"
                    ),
                ),
                (
                    "creado_el",
                    models.DateTimeField(auto_now_add=True, verbose_name="subido el"),
                ),
                (
                    "curso_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiales",
                        to="academico.cursoasignatura",
                        verbose_name="asignatura de curso",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiales",
                        to="calificaciones.periodoevaluacion",
                        verbose_name="período",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiales_subidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "material académico",
                "verbose_name_plural": "materiales académicos",
                "ordering": ["-creado_el"],
            },
        ),
    ]
