# Generated by Django 5.2.15 on 2026-06-12 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumnos", "0002_remove_perfilalumno_curso_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensaje", "Mensaje"),
                            ("solicitud_citacion", "Solicitud de citación"),
                        ],
                        default="mensaje",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("asunto", models.CharField(max_length=150, verbose_name="asunto")),
                ("cuerpo", models.TextField(verbose_name="mensaje")),
                (
                    "enviado_el",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado el"),
                ),
                ("leido", models.BooleanField(default=False, verbose_name="leído")),
                (
                    "destinatario",
                    models.ForeignKey(
                        limit_choices_to={"role": "profesor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensajes_recibidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profesor destinatario",
                    ),
                ),
                (
                    "pupilo",
                    models.ForeignKey(
                        blank=True,
                        help_text="El apoderado indica por cuál pupilo escribe.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensajes",
                        to="alumnos.perfilalumno",
                        verbose_name="alumno relacionado",
                    ),
                ),
                (
                    "remitente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_enviados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensaje",
                "verbose_name_plural": "mensajes",
                "ordering": ["-enviado_el"],
                "indexes": [
                    models.Index(
                        fields=["destinatario", "leido"],
                        name="comunicacio_destina_830ce9_idx",
                    )
                ],
            },
        ),
    ]
