# Generated by Django 5.2.15 on 2026-06-11 04:17

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_curso_profesor_jefe"),
        ("alumnos", "0002_remove_perfilalumno_curso_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="nombre"),
                ),
                (
                    "ponderacion_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="ponderación (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de evaluación",
                "verbose_name_plural": "tipos de evaluación",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="nombre")),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "puntaje_maximo",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="puntaje máximo"
                    ),
                ),
                (
                    "curso_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones",
                        to="academico.cursoasignatura",
                        verbose_name="asignatura de curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "evaluación",
                "verbose_name_plural": "evaluaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCalificacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "puntaje_obtenido",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="puntaje obtenido"
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.0")),
                            django.core.validators.MaxValueValidator(Decimal("7.0")),
                        ],
                        verbose_name="nota",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="fecha de registro"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="calificaciones.evaluacion",
                        verbose_name="evaluación",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="alumnos.matricula",
                        verbose_name="matrícula",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de calificación",
                "verbose_name_plural": "historical calificaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PeriodoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "anio_escolar",
                    models.PositiveSmallIntegerField(verbose_name="año escolar"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="fecha de término")),
            ],
            options={
                "verbose_name": "período de evaluación",
                "verbose_name_plural": "períodos de evaluación",
                "ordering": ["-anio_escolar", "fecha_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre", "anio_escolar"),
                        name="unique_periodo_nombre_anio",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluaciones",
                to="calificaciones.periodoevaluacion",
                verbose_name="período",
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluaciones",
                to="calificaciones.tipoevaluacion",
                verbose_name="tipo",
            ),
        ),
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntaje_obtenido",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="puntaje obtenido"
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.0")),
                            django.core.validators.MaxValueValidator(Decimal("7.0")),
                        ],
                        verbose_name="nota",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de registro"
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calificaciones",
                        to="alumnos.matricula",
                        verbose_name="matrícula",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calificaciones",
                        to="calificaciones.evaluacion",
                        verbose_name="evaluación",
                    ),
                ),
            ],
            options={
                "verbose_name": "calificación",
                "verbose_name_plural": "calificaciones",
                "ordering": ["-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["matricula", "evaluacion"],
                        name="calificacio_matricu_2cbc77_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evaluacion", "matricula"),
                        name="unique_calificacion_evaluacion_matricula",
                    )
                ],
            },
        ),
    ]
