# Generated by Django 5.2.15 on 2026-06-11 04:05

import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut_alumno",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[apps.accounts.validators.validar_rut_chileno],
                        verbose_name="RUT del alumno",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="fecha de nacimiento"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=255, verbose_name="dirección"),
                ),
                ("comuna", models.CharField(max_length=100, verbose_name="comuna")),
                (
                    "fecha_matricula",
                    models.DateField(verbose_name="fecha de matrícula"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumnos",
                        to="academico.curso",
                        verbose_name="curso",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"role": "alumno"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_alumno",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de alumno",
                "verbose_name_plural": "perfiles de alumnos",
                "ordering": ["usuario__last_name", "usuario__first_name"],
            },
        ),
        migrations.CreateModel(
            name="PerfilApoderado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relacion",
                    models.CharField(
                        choices=[
                            ("padre", "Padre"),
                            ("madre", "Madre"),
                            ("tutor", "Tutor(a)"),
                        ],
                        max_length=50,
                        verbose_name="relación con el alumno",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"role": "apoderado"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_apoderado",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de apoderado",
                "verbose_name_plural": "perfiles de apoderados",
                "ordering": ["usuario__last_name", "usuario__first_name"],
            },
        ),
        migrations.CreateModel(
            name="AlumnoApoderado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, verbose_name="es apoderado principal"
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_apoderados",
                        to="alumnos.perfilalumno",
                        verbose_name="alumno",
                    ),
                ),
                (
                    "apoderado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_alumnos",
                        to="alumnos.perfilapoderado",
                        verbose_name="apoderado",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo alumno-apoderado",
                "verbose_name_plural": "vínculos alumno-apoderado",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("alumno", "apoderado"), name="unique_alumno_apoderado"
                    )
                ],
            },
        ),
    ]
