# Generated by Django 5.2.15 on 2026-06-11 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0002_curso_profesor_jefe"),
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilalumno",
            name="curso",
        ),
        migrations.RemoveField(
            model_name="perfilalumno",
            name="fecha_matricula",
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio_escolar",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="año escolar"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("repitente", "Repitente"),
                            ("retirado", "Retirado"),
                            ("egresado", "Egresado"),
                        ],
                        default="regular",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "fecha_matricula",
                    models.DateField(verbose_name="fecha de matrícula"),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="alumnos.perfilalumno",
                        verbose_name="alumno",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="academico.curso",
                        verbose_name="curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "matrícula",
                "verbose_name_plural": "matrículas",
                "ordering": ["-anio_escolar", "alumno__usuario__last_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("alumno", "anio_escolar"),
                        name="unique_matricula_alumno_anio",
                    )
                ],
            },
        ),
    ]
