# Generated by Django 5.2.15 on 2026-06-12 19:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0003_materialacademico"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoCalendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                ("hora", models.TimeField(blank=True, null=True, verbose_name="hora")),
                (
                    "lugar",
                    models.CharField(blank=True, max_length=150, verbose_name="lugar"),
                ),
            ],
            options={
                "verbose_name": "evento del calendario",
                "verbose_name_plural": "eventos del calendario",
                "ordering": ["fecha", "hora"],
            },
        ),
        migrations.CreateModel(
            name="ItemGaleria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="título")),
                (
                    "anio",
                    models.PositiveSmallIntegerField(default=2026, verbose_name="año"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galeria/%Y/",
                        verbose_name="imagen",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Ej: https://www.youtube.com/embed/XXXXXXX",
                        verbose_name="URL de video (embed)",
                    ),
                ),
                (
                    "creado_el",
                    models.DateTimeField(auto_now_add=True, verbose_name="subido el"),
                ),
            ],
            options={
                "verbose_name": "ítem de galería",
                "verbose_name_plural": "galería",
                "ordering": ["-anio", "-creado_el"],
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                (
                    "bajada",
                    models.CharField(
                        help_text="Resumen corto que se muestra en los listados.",
                        max_length=300,
                        verbose_name="bajada",
                    ),
                ),
                ("cuerpo", models.TextField(verbose_name="cuerpo")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="noticias/%Y/",
                        verbose_name="imagen",
                    ),
                ),
                (
                    "publicada",
                    models.BooleanField(default=True, verbose_name="publicada"),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="fecha"
                    ),
                ),
            ],
            options={
                "verbose_name": "noticia",
                "verbose_name_plural": "noticias",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MediadorEscolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="nombre del mediador"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mediadores",
                        to="academico.curso",
                        verbose_name="curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "mediador escolar",
                "verbose_name_plural": "mediadores escolares",
                "ordering": ["curso__nivel_id", "curso__letra", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_postulante",
                    models.CharField(
                        max_length=150, verbose_name="nombre del postulante"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="fecha de nacimiento"),
                ),
                (
                    "nombre_apoderado",
                    models.CharField(
                        max_length=150, verbose_name="nombre del apoderado"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="correo electrónico de contacto"
                    ),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="teléfono")),
                ("mensaje", models.TextField(blank=True, verbose_name="mensaje")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nueva", "Nueva"),
                            ("en_revision", "En revisión"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="nueva",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "creado_el",
                    models.DateTimeField(auto_now_add=True, verbose_name="recibida el"),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postulaciones",
                        to="academico.niveleducacional",
                        verbose_name="nivel al que postula",
                    ),
                ),
            ],
            options={
                "verbose_name": "postulación",
                "verbose_name_plural": "postulaciones",
                "ordering": ["-creado_el"],
            },
        ),
    ]
