# Generated by Django 5.2.15 on 2026-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_publica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipoConvivencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="nombre")),
                ("cargo", models.CharField(max_length=120, verbose_name="cargo")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="descripción"
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Menor número aparece primero.",
                        verbose_name="orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "integrante del equipo de convivencia",
                "verbose_name_plural": "equipo de convivencia",
                "ordering": ["orden", "nombre"],
            },
        ),
    ]
