# Generated by Django 5.2.15 on 2026-06-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_publica", "0003_equipo_convivencia_datos"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MediadorEscolar",
        ),
    ]
